---
name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Validation:
    runs-on: ubuntu-20.04
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@v0.2.0
        with:
          command: validate
          arguments: -syntax-only
          target: packer.pkr.hcl
